Academy_Book/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from django.contrib import admin
from django.urls import path, re_path, include

from accounts.views import home
from hashTags.views import HashTagView

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('api/', include('analytics.urls')),
    path('accounts/', include('accounts.urls', namespace="profiles")),
    path('api/', include('accounts.api.urls', namespace="profiles-api")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('calendar/', include('cal.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('api/posts/', include('posts.api.urls', namespace='posts-api')),
    path('', home, name='home'),
    re_path(r'^tags/(?P<hashtag>.*)/$', HashTagView.as_view(), name='hashtag'),
    path('api/', include('comments.api.urls', namespace='comment')),

]

# urlpatterns += i18n_patterns(
#     path('admin/', admin.site.urls),
#     path('api/', include('analytics.urls')),
#     path('accounts/', include('accounts.urls', namespace="profiles")),
#     path('api/', include('accounts.api.urls', namespace="profiles-api")),
#     path('accounts/', include('django.contrib.auth.urls')),
#     path('accounts/', include('allauth.urls')),
#     path('posts/', include('posts.urls', namespace='posts')),
#     path('api/posts/', include('posts.api.urls', namespace='posts-api')),
#     path('', home, name='home'),
#     re_path(r'^tags/(?P<hashtag>.*)/$', HashTagView.as_view(), name='hashtag'),
#     path('api/', include('comments.api.urls', namespace='comment')),
#     prefix_default_language=False
#
# )

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, re_path
from .views import (login_view,
                    register,
                    join,
                    checkout,
                    settings,
                    activate_account,
                    logout_view,
                    UserDetailView,
                    UserFollow,
                    )
from .friendsViews import (user_list,

                           send_friend_request,
                           cancel_friend_request,
                           accept_friend_request,
                           delete_friend_request)

app_name = "profiles"

urlpatterns = [
    path('register/', register, name="register"),
    path('join/', join, name="join"),
    path('checkout/', checkout, name="checkout"),
    path('setting/', settings, name="setting"),
    path('signin/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            activate_account,
            name='activate'),
    path('user-detail/<str:username>/', UserDetailView.as_view(), name="user-detail"),
    path('<str:username>/user-follow/', UserFollow.as_view(), name="user-follow"),
    path('user-list', user_list, name='user-list'),

    path('friend-request/send/<int:pk>/', send_friend_request),
    path('friend-request/cancel/<int:pk>/', cancel_friend_request),
    path('friend-request/accept/<int:pk>/', accept_friend_request),
    path('friend-request/delete/<int:pk>/', delete_friend_request),

]

cal/urls.py
from django.urls import path

from .views import CalendarView, event

app_name = 'cal'

urlpatterns = [
    path('', CalendarView.as_view(), name='calendar'),
    path('event/new/', event, name='event_new'),
    path('event/edit/<int:event_id>/', event, name='event_edit'),
]

posts/api/urls.py
from django.urls import path

from .views import (PostListApiView,
                    PostCreateApiView,
                    RePostApiView,
                    LikedToggleAPIView,
                    PostDetailAPIView, SearchListApiView)

app_name = 'posts-api'

urlpatterns = [
    path('', PostListApiView.as_view(), name='list-api'),
    path('create-api/', PostCreateApiView.as_view(), name='create-api'),
    path('<int:pk>/like/', LikedToggleAPIView.as_view(), name='like'),
    path('<int:pk>/', PostDetailAPIView.as_view(), name='detail'),
    path('<int:pk>/repost/', RePostApiView.as_view(), name='repost'),

    path("search-api/", SearchListApiView.as_view(), name="search-api")


]

posts/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from .views import (PostDetailView,
                    PostListView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView,
                    RePostView, SearchView
                    )


app_name = 'posts'

urlpatterns = [
    path('', RedirectView.as_view(url='/')),
    path('create-post/', PostCreateView.as_view(), name='create-post'),
    path('post-detail-cbv/<int:pk>/', PostDetailView.as_view(), name='post-detail-cbv'),
    path('<int:pk>/repost/', RePostView.as_view(), name='repost'),
    path('post-list/', PostListView.as_view(), name='post-list'),
    path('<int:pk>/post-update/', PostUpdateView.as_view(), name='post-update'),
    path('<int:pk>/post-delete/', PostDeleteView.as_view(), name='post-delete'),
    path("search/", SearchView.as_view(), name="search"),



]

posts/forms.py
from django import forms

from .models import Post


class PostModelForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.Textarea(attrs={
        'placeholder': 'Your Content',
        "class": "form-control"
    }))

    class Meta:
        model = Post
        fields = [
            # 'user',
            'content'
        ]

posts/api/views.py
from django.contrib.contenttypes.models import ContentType
from rest_framework import generics
from django.shortcuts import get_object_or_404, redirect, render
from urllib.parse import quote_plus
from django.utils import translation
from rest_framework.permissions import IsAuthenticated

from analytics.mixins import ObjectViewedMixin
from rest_framework import permissions
from rest_framework.views import APIView
from rest_framework.response import Response
from django.db.models import Q
from .pagination import StandardResultsPagination

from posts.models import Post
from .serializers import PostSerializer
from ..mixins import Paid


class LikedToggleAPIView(APIView):
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, pk=None, format=None):
        post_qs = Post.objects.filter(pk=pk)
        message = "Not Allowed"
        if request.user.is_authenticated:
            is_liked = Post.objects.like_toggle(request.user, post_qs.first())
            return Response({'liked': is_liked})
        return Response({"message": message}, status=400)


class RePostApiView(APIView):
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, pk=None, format=None):
        post_qs = Post.objects.filter(pk=pk)
        message = "Not Allowed"
        if post_qs.exists() and post_qs.count() == 1:
            new_post = Post.objects.repost(request.user, post_qs.first())
            if new_post is not None:
                data = PostSerializer(new_post).data
                return Response(data)
            message = "Cannot post "
        return Response({"message": message}, status=400)


class PostCreateApiView(generics.CreateAPIView):
    serializer_class = PostSerializer

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class SearchListApiView(generics.ListAPIView):
    queryset = Post.objects.all().order_by("-timestamp")
    serializer_class = PostSerializer
    pagination_class = StandardResultsPagination

    def get_serializer_context(self, *args, **kwargs):
        context = super(SearchListApiView, self).get_serializer_context(*args, **kwargs)
        context['request'] = self.request
        return context

    def get_queryset(self, *args, **kwargs):
        qs = self.queryset
        query = self.request.GET.get("q", None)
        if query is not None:
            qs = qs.filter(
                Q(content__icontains=query) |
                Q(user__username__icontains=query)
            )
        return qs


class PostListApiView(Paid, generics.ListAPIView):
    serializer_class = PostSerializer
    permission_class = (IsAuthenticated, )
    pagination_class = StandardResultsPagination

    def get_serializer_context(self, *args, **kwargs):
        context = super(PostListApiView, self).get_serializer_context(*args, **kwargs)
        context['request'] = self.request
        return context

    def get_queryset(self, *args, **kwargs):
        requested_user = self.kwargs.get("username")
        if requested_user:
            qs = Post.objects.filter(user__username=self.request.user).order_by("-timestamp")
        else:
            i_am_following = self.request.user.profile.get_following()
            qs1 = Post.objects.filter(user__in=i_am_following)
            qs2 = Post.objects.filter(user=self.request.user)
            qs = (qs1 | qs2).distinct().order_by("-timestamp")
        query = self.request.GET.get("q", None)
        if query is not None:
            qs = qs.filter(
                Q(content__icontains=query) |
                Q(user__username__icontains=query)
            )
        return qs


class PostDetailAPIView(ObjectViewedMixin, generics.ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [permissions.AllowAny]
    pagination_class = StandardResultsPagination

    def get_queryset(self, *args, **kwargs):
        post_id = self.kwargs.get('pk')
        instance = Post.objects.filter(pk=post_id)

        if instance.exists() and instance.count() == 1:
            parent_obj = instance.first()
            qs1 = parent_obj.get_children()
            instance = (instance | qs1).distinct().extra(select={"parent_id_null": "parent_id IS NULL"})
        # object_viewed_signal.send(qs.__class__, instance=qs, request=request)
        return instance.order_by("-parent_id_null", "timestamp")

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.utils import translation
from urllib.parse import quote_plus
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext as _
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView

from django.contrib.auth import get_user_model

from Academy_Book.language import Translate
from accounts.models import Customer
from comments.models import Comment
from .mixins import FormUserNeededMixin, UserOwnerMixin, Paid
from analytics.mixins import ObjectViewedMixin
from django.views import View
from django.urls import reverse_lazy
from .models import Post

from .forms import PostModelForm

User = get_user_model()


class RePostView(View):
    def get(self, request, pk, *args, **kwargs):
        post = get_object_or_404(Post, pk=pk)
        if request.user.is_authenticated:
            new_post = Post.objects.repost(request.user, post)
            return HttpResponseRedirect('/posts/post-list/')
        return HttpResponseRedirect(post.get_absolute_url())


class PostCreateView(LoginRequiredMixin, FormUserNeededMixin, CreateView):
    form_class = PostModelForm
    template_name = 'posts/create.html'
    # success_url = reverse_lazy('posts:post-detail-cbv')
    # login_url = "/accounts/login/"


class PostUpdateView(LoginRequiredMixin, UserOwnerMixin, UpdateView):
    queryset = Post.objects.all()
    form_class = PostModelForm
    template_name = 'posts/update.html'


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'posts/delete_confirm.html'
    success_url = reverse_lazy('posts:post-list')


class PostDetailView(Translate, ObjectViewedMixin, DetailView):
    queryset = Post.objects.all()
    template_name = 'posts/post_detail.html'


class PostListView(LoginRequiredMixin, ListView):
    queryset = Post.objects.all()

    def get_queryset(self, *args, **kwargs):
        request = self.request

        qs = Post.objects.all()
        query = request.GET.get("q", None)
        if query is not None:
            qs = qs.filter(
               Q(content__icontains=query) |
               Q(user__username__icontains=query)
            )
        return qs

    def get_context_data(self, *args, **kwargs):
        context = super(PostListView, self).get_context_data(*args, **kwargs)
        title = _('Homepage')
        notify = _("Notifications")
        profile = _("Profile")
        settings = _("Settings")
        search = _("Search")
        context['create_form'] = PostModelForm()
        context['create_url'] = reverse_lazy('posts:create-post')
        context['title'] = title
        context['notify'] = notify
        context['profile'] = profile
        context['settings'] = settings
        context['search'] = search

        return context


class SearchView(Translate, View):
    def get(self, request, *args, **kwargs):
        query = request.GET.get("q")
        qs = None
        if query:
            qs = User.objects.filter(
                Q(username__icontains=query)
            )
        context = {
            "users": qs
        }
        title = _('Homepage')
        notify = _("Notifications")
        profile = _("Profile")
        settings = _("Settings")
        search = _("Search")
        context['title'] = title
        context['notify'] = notify
        context['profile'] = profile
        context['settings'] = settings
        context['search'] = search
        return render(request, "posts/search.html", context)

posts/templates/plans/checkout.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row justify-content-center">
      <div class="col-md-4 order-md-2 mb-4">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted">Your cart</span>
          <span class="badge badge-secondary badge-pill">1</span>
        </h4>
        <ul class="list-group mb-3">
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">AcademyBook Premium</h6>
              <small class="text-muted">{{ plan|title }}</small>
            </div>
            <span class="text-muted">Rs.{{ og_dollar }}</span>
          </li>
          {% if coupon != 'none' %}
          <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">Promo code</h6>
              <small>{{ coupon|upper }}</small>
            </div>
            <span class="text-success">-Rs{{ coupon_dollar }}</span>
          </li>
          {% endif %}
          <li class="list-group-item d-flex justify-content-between">
            <span>Total (NPR)</span>
            <strong>Rs.{{ final_dollar }}</strong>
          </li>
        </ul>

        <form class="card p-2" action="{% url 'profiles:checkout' %}" method="GET">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Promo code" name="coupon">
            <input type="hidden" value="{{ plan }}" name="plan" />
            <div class="input-group-append">
              <button type="submit" class="btn btn-secondary">Redeem</button>
            </div>
          </div>
        </form>

        <div class="text-center pt-3">
        <form action="{% url 'profiles:checkout' %}" method="POST">
          {% csrf_token %}
          <script
            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="pk_test_PQEdj3xPUcigc9eAsXA31J8900h1BYhGg4"
            data-amount="{{ price }}"
            data-name="Nick Fitness, LLC"
            data-description="Premium Membership"
            data-email="{{ user.email }}"
            data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
            data-locale="auto">
          </script>
          <input type="hidden" value="{{ plan }}" name="plan" />
          <input type="hidden" value="{{ coupon }}" name="coupon" />
        </form>
        </div>
        </div>
      </div>
      </div>



{% endblock %}

posts/templates/plans/join.html
{% extends 'base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Academy Book Premium</h1>
  <p class="lead">Get the body you've always dreamed of. Live the healthy life that you know you should. From workouts to nutrition, you have all the tools you need to succeed. It's all yours with Nick Fitness Premium.</p>
</div>

<div class="container">
  <div class="card-deck mb-3 text-center">
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Monthly</h4>
      </div>
     <div class="card-body">
        <h1 class="card-title pricing-card-title">$100 <small class="text-muted">/ yr</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>Detailed Workout Plans</li>
          <li>Nutrition Guides</li>
          <li>Scientific Studies Breakdown</li>
          <li>Weekly Members Only Email</li>
        </ul>
        <a href="{% url 'profiles:checkout' %}?plan=monthly"><button type="button" class="btn btn-lg btn-block btn-primary">Get started</button></a>
      </div>
    </div>

    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Yearly<small class="text-primary">  Save $20!</small></h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$100 <small class="text-muted">/ yr</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>Detailed Workout Plans</li>
          <li>Nutrition Guides</li>
          <li>Scientific Studies Breakdown</li>
          <li>Weekly Members Only Email</li>
        </ul>
        <a href="{% url 'profiles:checkout' %}?plan=yearly"><button type="button" class="btn btn-lg btn-block btn-primary">Get started</button></a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

posts/templates/plans/plan.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<h1>{{ plan.title}}</h1>
<p>{{ plan.text }}</p>
</div>
{% endblock %}