Academy_Book/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from django.contrib import admin
from django.urls import path, re_path, include

from accounts.views import home
from hashTags.views import HashTagView

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('api/', include('analytics.urls')),
    path('accounts/', include('accounts.urls', namespace="profiles")),
    path('api/', include('accounts.api.urls', namespace="profiles-api")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('calendar/', include('cal.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('api/posts/', include('posts.api.urls', namespace='posts-api')),
    path('', home, name='home'),
    re_path(r'^tags/(?P<hashtag>.*)/$', HashTagView.as_view(), name='hashtag'),
    path('api/', include('comments.api.urls', namespace='comment')),

]

# urlpatterns += i18n_patterns(
#     path('admin/', admin.site.urls),
#     path('api/', include('analytics.urls')),
#     path('accounts/', include('accounts.urls', namespace="profiles")),
#     path('api/', include('accounts.api.urls', namespace="profiles-api")),
#     path('accounts/', include('django.contrib.auth.urls')),
#     path('accounts/', include('allauth.urls')),
#     path('posts/', include('posts.urls', namespace='posts')),
#     path('api/posts/', include('posts.api.urls', namespace='posts-api')),
#     path('', home, name='home'),
#     re_path(r'^tags/(?P<hashtag>.*)/$', HashTagView.as_view(), name='hashtag'),
#     path('api/', include('comments.api.urls', namespace='comment')),
#     prefix_default_language=False
#
# )

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/api/urls.py
from django.urls import path

from django.views.generic.base import RedirectView

app_name = 'profiles-api'

from posts.api.views import (PostListApiView)

urlpatterns = [
    path('<str:username>/posts/', PostListApiView.as_view(), name="list-api")
]

accounts/urls.py
from django.urls import path, re_path
from .views import (login_view,
                    register,
                    join,
                    checkout,
                    settings,
                    activate_account,
                    logout_view,
                    UserDetailView,
                    UserFollow,
                    )
from .friendsViews import (user_list,

                           send_friend_request,
                           cancel_friend_request,
                           accept_friend_request,
                           delete_friend_request)

app_name = "profiles"

urlpatterns = [
    path('register/', register, name="register"),
    path('join/', join, name="join"),
    path('checkout/', checkout, name="checkout"),
    path('setting/', settings, name="setting"),
    path('signin/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            activate_account,
            name='activate'),
    path('user-detail/<str:username>/', UserDetailView.as_view(), name="user-detail"),
    path('<str:username>/user-follow/', UserFollow.as_view(), name="user-follow"),
    path('user-list', user_list, name='user-list'),

    path('friend-request/send/<int:pk>/', send_friend_request),
    path('friend-request/cancel/<int:pk>/', cancel_friend_request),
    path('friend-request/accept/<int:pk>/', accept_friend_request),
    path('friend-request/delete/<int:pk>/', delete_friend_request),

]

cal/urls.py
from django.urls import path

from .views import CalendarView, event

app_name = 'cal'

urlpatterns = [
    path('', CalendarView.as_view(), name='calendar'),
    path('event/new/', event, name='event_new'),
    path('event/edit/<int:event_id>/', event, name='event_edit'),
]

posts/models.py
import re
from django.db.models.signals import post_save, pre_save
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from markdown_deux import markdown
from comments.models import Comment
from hashTags.signals import parsed_hashtags
from .utils import get_read_time
from .validators import validate_content


class PostManager(models.Manager):
    def repost(self, user, parent_obj):
        if parent_obj.parent:
            og_parent = parent_obj.parent
        else:
            og_parent = parent_obj
        qs = self.get_queryset().filter(user=user, parent=og_parent, reply=False)
        if qs.exists():
            return None
        obj = self.model(
            parent=og_parent,
            user=user,
            content=parent_obj.content
        )
        obj.save()
        return obj

    def like_toggle(self, user, post_obj):
        if user in post_obj.liked.all():
            is_liked = True
            post_obj.liked.remove(user)
        else:
            is_liked = False
            post_obj.liked.add(user)
        return is_liked


def upload_location(instance, filename):
    # filebase, extension = filename.split(".")
    # return "%s/%s.%s" %(instance.id, instance.id, extension)
    PostModel = instance.__class__
    new_id = PostModel.objects.order_by("id").last().id + 1
    """
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
    return "%s/%s" % (new_id, filename)


class Post(models.Model):
    parent = models.ForeignKey("self", blank=True, null=True, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              )
    content = models.TextField(max_length=500, validators=[validate_content])
    liked = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='liked')
    reply = models.BooleanField(verbose_name='Is a reply?', default=False)
    premium = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = PostManager()

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse("posts:post-detail-cbv", kwargs={"pk": self.pk})

    def get_markdown(self):
        content = self.content
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

    def get_posts_count(self):
        return Post.objects.filter(content__in=self).count()

    def get_parent(self):
        the_parent = self
        if self.parent:
            the_parent = self.parent
        return the_parent

    def get_children(self):
        parent = self.get_parent()
        qs = Post.objects.filter(parent=parent)
        qs_parent = Post.objects.filter(pk=parent.pk)
        return (qs | qs_parent)

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)

    @property
    def get_content_type(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)

    @classmethod
    def user_assets(cls, user):
        return Post.objects.select_related('Users').filter(user=user).count()

    class Meta:
        ordering = ['-timestamp']


def create_slug(instance, new_slug=None):
    slug = slugify(instance.user.username)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time_var = get_read_time(html_string)
        instance.read_time = read_time_var


pre_save.connect(pre_save_post_receiver, sender=Post)


def post_save_receiver(sender, instance, created, *args, **kwargs):
    if created and not instance.parent:
        # notify a user
        user_regex = r'@(?P<username>[\w.@+-]+)'
        username = re.findall(user_regex, instance.content)

        hash_regex = r'#(?P<hashtag>[\w\d-]+)'
        hashtags = re.findall(hash_regex, instance.content)
        parsed_hashtags.send(sender=instance.__class__, hashtag_list=hashtags)


post_save.connect(post_save_receiver, sender=Post)

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView
from django.views import View

from Academy_Book.language import Translate
# from .signals import user_logged_in
from django.contrib.auth import get_user_model, login, logout
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.core.mail import EmailMessage
from celery import shared_task
from time import sleep
import stripe
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import render_to_string

from .signals import user_logged_in
from .token_generator import account_activation_token
from .models import Profile, Customer
from .tasks import sleepy
from .forms import UserCreationForm, UserLoginForm, UserUpdateForm

User = get_user_model()

stripe.api_key = 'sk_test_1YjooVfuUWXkzdTeUrLtJHTe00lxb7H6Tk'


def home(request):
    return render(request, "home.html", {})


def join(request):
    return render(request, 'plans/join.html')


@login_required
def checkout(request):
    try:
        if request.user.customer.membership:
            return redirect('posts:post-list')
    except Customer.DoesNotExist:
        pass
    coupons = {'halloween': 31, 'welcome': 10}
    if request.method == 'POST':
        stripe_customer = stripe.Customer.create(email=request.user.email, source=request.POST['stripeToken'])
        plan = 'plan_HCgG3B8clQv5cl'
        if request.POST['plan'] == 'yearly':
            plan = 'plan_HCgGkYAOPMRYAI'
        if request.POST['coupon'] in coupons:
            percentage = coupons[request.POST['coupon'].lower()]
            try:
                coupon = stripe.Coupon.create(duration='once', id=request.POST['coupon'].lower(),
                                              percentage_off=percentage)
            except:
                pass
            subscription = stripe.Subscription.create(customer=stripe_customer.id, items=[{'plan': plan}],
                                                      coupon=request.POST['coupon'].lower())
        else:
            subscription = stripe.Subscription.create(customer=stripe_customer.id, items=[{'plan': plan}])
        customer = Customer()
        customer.user = request.user
        customer.stripe_id = stripe_customer.id
        customer.membership = True
        customer.cancel_at_period_end = False
        customer.stripe_subscription_id = subscription.id
        customer.save()
        return redirect('posts:post-list')
    else:
        plan = 'monthly'
        coupon = 'none'
        price = 1000
        og_dollar = 1000
        coupon_dollar = 0
        final_dollar = 1000
        if request.method == 'GET' and 'plan' in request.GET:
            if request.GET['plan'] == 'yearly':
                plan = 'yearly'
                price = 10000
                og_dollar = 10000
                final_dollar = 10000

        if request.method == 'GET' and 'coupon' in request.GET:
            if request.GET['coupon'].lower() in coupons:
                coupon = request.GET['coupon'].lower()
                percentage = coupons[coupon]
                coupon_price = int((percentage / 100) * price)
                price = price - coupon_price
                coupon_dollar = str(coupon_price) + '.' + str(coupon_price)[-2:]
                final_dollar = str(price) + '.' + str(price)[-2:]

    return render(request, 'plans/checkout.html', {
        'plan': plan, 'coupon': coupon,
        'price': price, 'og_dollar': og_dollar, 'final_dollar': final_dollar,
        'coupon_dollar': coupon_dollar})


def settings(request):
    return render(request, 'plans/settings.html')


@shared_task()
def register(request, *args, **kwargs):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        current_site = get_current_site(request)
        email_subject = 'Activate your account'
        message = render_to_string('activate_account.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)).encode().decode(),
            'token': account_activation_token.make_token(user),
        })
        to_email = form.cleaned_data.get('email')
        email = EmailMessage(email_subject, message, to=[to_email])
        sleep(10)
        email.send()

        return HttpResponse('We have send You an email, please confirm your email address to complete registration')
    else:
        form = UserCreationForm()
    context = {
        "form": form
    }
    return render(request, 'accounts/register.html', context)


def activate_account(request, uidb64, token, backend='django.contrib.auth.backends.ModelBackend'):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend)
        return HttpResponse('Your account has been activate successfully')
    else:
        return HttpResponse('Activation link is invalid!')


def login_view(request, backend='django.contrib.auth.backends.ModelBackend', user=None, *args, **kwargs, ):
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        user_obj = form.cleaned_data.get('user_obj')
        login(request, user_obj, backend)
        user_logged_in.send(user_obj.__class__, instance=user_obj, request=request)
        return HttpResponseRedirect('/')

    context = {
        "form": form
    }
    return render(request, "accounts/login.html", context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/accounts/login/')


class UserDetailView(LoginRequiredMixin, Translate, DetailView):
    queryset = User.objects.all()
    template_name = "accounts/myuser_detail.html"

    def get_object(self, queryset=None):
        return get_object_or_404(User, username__iexact=self.kwargs.get('username'))

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailView, self).get_context_data(*args, **kwargs)
        context['following'] = Profile.objects.is_following(self.request.user, self.get_object())
        return context


class UserFollow(View):
    def get(self, request, username, *args, **kwargs):
        toggleUser = get_object_or_404(User, username__iexact=username)
        if request.user.is_authenticated:
            is_following = Profile.objects.toggle_follow(request.user, toggleUser)
        return redirect("profiles:user-detail", username=username)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% load account socialaccount %}

{% block title %}
    Sign-In
{% endblock %}

{% block content %}
    <h1>{% trans "Sign In" %}</h1>

{% get_providers as socialaccount_providers %}

{% if socialaccount_providers %}
<p>Please sign in with one
of your existing third party accounts. Or, <a href="{% url 'profiles:register' %}">sign up</a>
for a {{ site_name }} account and sign in below</p>

<div class="socialaccount_ballot">

  <ul class="socialaccount_providers">
    {% include "socialaccount/snippets/provider_list.html" with process="login" %}
  </ul>

  <div class="login-or">{% trans 'or' %}</div>

</div>

{% include "socialaccount/snippets/login_extra.html" %}

{% else %}
<p>{% blocktrans %}If you have not created an account yet, then please
<a href="{{ signup_url }}">sign up</a> first.{% endblocktrans %}</p>
{% endif %}
    <form class="form-signin" action="." method="post"> {% csrf_token %}
      {{form|crispy}}
      <button type="submit" name="button">Login</button>
    {% if redirect_field_value %}
  <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
  {% endif %}
  <a class="button secondaryAction" href="{% url 'account_reset_password' %}">{% trans "Forgot Password?" %}</a>

    </form>

{% endblock %}




{% load crispy_forms_tags %}
{{form|crispy}}

accounts/templates/accounts/myuser_detail.html
{% extends "base.html" %}

{% block title %}
    Profile
{% endblock %}

{% block script %}
     <script>

      $(document).ready(function () {
            loadPostContainer("post-container")
        });
    </script>
{% endblock %}

{% block content %}
    <div class="row">
    <div class="col-sm-3 col-xs-12" >
        <h1>{{ object.username }}</h1>
         <hr/>
        <p> Followers: {{ object.follow.all.count }}</p>
        <p><a class="btn btn-link" href="{% url 'profiles:user-follow' username=object.username %}">
            {% if following %}
                UnFollow
                {% else %}
                Follow
            {% endif %}

        </a></p>

    </div>

    <div class="col-sm-6 col-xs-12">
        <h1>Posts</h1>
     <hr/>
{#        {% for post in object.post_set.all %}#}
{#            {{ post }} </br>#}
{##}
{#        {% endfor %}#}

                        <div class=" lead card mb-3" id="post-container" data-url="/api/{{object.username}}/posts/">

                        </div>

        <small class="d-block text-right mt-3">
          <a href="#" id="loadmore">Load More</a>
        </small>
     </div>
    <hr/>
     <div class="col-sm-3 col-xs-12">
          <h1>Following <small class="badge-primary">{{ object.profile.get_following.count }}</small></h1>
     <hr/>
        {% for user in object.profile.get_following %}
            <a href="/{{ user.username }}">{{ user.username }}</a>
             </br>
            {% empty %}
            <h1> Not following any user</h1>

        {% endfor %}
    <hr/>
     <h1>Followed By</h1>
        {% for profile in object.follow.all %}
            <a href="/{{ profile.user.username }}">{{ profile.user.username }}</a> </br>
            {% empty %}
            <h4> Not followed by any user</h4>
             {% endfor %}
     </div>

    </div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}
    
{% endblock %}


{% block content %}
    <div class="container text-center">
	<span><a href="/users/">Home</a></span>

	{% if request.user == u %}

		<h1>Friends</h1>

		{% for friend in friends_list %}
			<a href="{{ friend.user.profile.get_absolute_url }}">{{ friend.user.username }}</a>
		{% endfor %}
		<hr>
		<h2>Sent Friend requests</h2>
		<ul>
		{% for s_request in sent_friend_requests %}
			<li>{{ s_request.to_user.username }}</li>
		{% endfor %}
		</ul>
		<hr>
		<h2>Received Friend requests</h2>

		{% for r_request in rec_friend_requests %}
			<p><a href="{{ r_request.from_user.profile.get_slug_url }}">{{ r_request.from_user.username }}</a></p>
			<small><a class='btn btn-primary' href="/accounts/friend-request/accept/{{ r_request.from_user.id }}">Accept</a></small>
			<small><a class='btn btn-warning' href="/accounts/friend-request/delete/{{ r_request.from_user.id }}">Ignore</a></small>
		{% endfor %}


	{% else %}

		{% if button_status == 'not_friend' %}
			<small><a class='btn btn-primary' href="/accounts/friend-request/send/{{ u.id }}">Add Friend</a></small>
		{% elif button_status == 'friend_request_sent' %}
			<small><a class="btn btn-warning" href="/accounts/friend-request/cancel/{{ u.id }}">Cancel Request</a></small>
		{% endif %}

	{% endif %}

	</div>


{% endblock %}

accounts/templates/accounts/register.html
{%  extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Register
{% endblock %}

{% block content %}
     <form  class=" my-5" action="." method="post"> {% csrf_token %}
{#          {% for field in form %}#}
{#      <p>#}
{#        {{ field.label_tag }}<br>#}
{#        {{ field }}#}
{#        {% if field.help_text %}#}
{#          <small style="display: none">{{ field.help_text }}</small>#}
{#        {% endif %}#}
{#        {% for error in field.errors %}#}
{#          <p style="color: red">{{ error }}</p>#}
{#        {% endfor %}#}
{#              </p>#}
{#      {% endfor %}#}

      {{form|crispy}}
      <button type="submit" name="button">Register</button>
    </form>

{% endblock %}

accounts/templates/accounts/user_list.html
{% extends "base.html" %}

{% block title %}

{% endblock %}


{% block content %}
<ul>
	{% for user_p in users %}
		<li><a href="{{ user_p.get_absolute_url }}">{{ user_p }}</a></li>
	{% endfor %}
	</ul>

{% endblock %}