Academy_Book/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from django.contrib import admin
from django.urls import path, re_path, include

from accounts.views import home
from hashTags.views import HashTagView

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('api/', include('analytics.urls')),
    path('accounts/', include('accounts.urls', namespace="profiles")),
    path('api/', include('accounts.api.urls', namespace="profiles-api")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('calendar/', include('cal.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('api/posts/', include('posts.api.urls', namespace='posts-api')),
    path('', home, name='home'),
    re_path(r'^tags/(?P<hashtag>.*)/$', HashTagView.as_view(), name='hashtag'),
    path('api/', include('comments.api.urls', namespace='comment')),

]

# urlpatterns += i18n_patterns(
#     path('admin/', admin.site.urls),
#     path('api/', include('analytics.urls')),
#     path('accounts/', include('accounts.urls', namespace="profiles")),
#     path('api/', include('accounts.api.urls', namespace="profiles-api")),
#     path('accounts/', include('django.contrib.auth.urls')),
#     path('accounts/', include('allauth.urls')),
#     path('posts/', include('posts.urls', namespace='posts')),
#     path('api/posts/', include('posts.api.urls', namespace='posts-api')),
#     path('', home, name='home'),
#     re_path(r'^tags/(?P<hashtag>.*)/$', HashTagView.as_view(), name='hashtag'),
#     path('api/', include('comments.api.urls', namespace='comment')),
#     prefix_default_language=False
#
# )

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, re_path
from .views import (login_view,
                    register,
                    join,
                    checkout,
                    settings,
                    activate_account,
                    logout_view,
                    UserDetailView,
                    UserFollow,
                    )
from .friendsViews import (user_list,

                           send_friend_request,
                           cancel_friend_request,
                           accept_friend_request,
                           delete_friend_request)

app_name = "profiles"

urlpatterns = [
    path('register/', register, name="register"),
    path('join/', join, name="join"),
    path('checkout/', checkout, name="checkout"),
    path('setting/', settings, name="setting"),
    path('signin/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            activate_account,
            name='activate'),
    path('user-detail/<str:username>/', UserDetailView.as_view(), name="user-detail"),
    path('<str:username>/user-follow/', UserFollow.as_view(), name="user-follow"),
    path('user-list', user_list, name='user-list'),

    path('friend-request/send/<int:pk>/', send_friend_request),
    path('friend-request/cancel/<int:pk>/', cancel_friend_request),
    path('friend-request/accept/<int:pk>/', accept_friend_request),
    path('friend-request/delete/<int:pk>/', delete_friend_request),

]

cal/urls.py
from django.urls import path

from .views import CalendarView, event

app_name = 'cal'

urlpatterns = [
    path('', CalendarView.as_view(), name='calendar'),
    path('event/new/', event, name='event_new'),
    path('event/edit/<int:event_id>/', event, name='event_edit'),
]

posts/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from .views import (PostDetailView,
                    PostListView,
                    PostCreateView,
                    PostUpdateView,
                    PostDeleteView,
                    RePostView, SearchView
                    )


app_name = 'posts'

urlpatterns = [
    path('', RedirectView.as_view(url='/')),
    path('create-post/', PostCreateView.as_view(), name='create-post'),
    path('post-detail-cbv/<int:pk>/', PostDetailView.as_view(), name='post-detail-cbv'),
    path('<int:pk>/repost/', RePostView.as_view(), name='repost'),
    path('post-list/', PostListView.as_view(), name='post-list'),
    path('<int:pk>/post-update/', PostUpdateView.as_view(), name='post-update'),
    path('<int:pk>/post-delete/', PostDeleteView.as_view(), name='post-delete'),
    path("search/", SearchView.as_view(), name="search"),



]

templates/activate_account.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://127.0.0.1:8000{% url 'profiles:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/activation_request.html
{% extends "base.html" %}

{% block title %}
    Activation
{% endblock %}

{% block content %}
    {% autoescape off %}
Hi {{ user.username }},

Please click the following link to confirm your registration:

http://127.0.0.1:8000{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}
{% endblock %}

templates/form.html
{% load crispy_forms_tags %}
    <form class='form {% if form_class %} {{ form_class }}

    {% endif %}' method="POST" action="{% if action_url %}
    {{ action_url }}
    {% endif %} ">
    {% csrf_token %}

        {{ form|crispy }}
    <input class="btn btn-dark my-3" type="submit" value="{{btn_title}}">
    </form>

templates/home.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
        <main role="main" class="container">
        <div class="row">
        <div class="col-md-8 blog-main">

      <div class="my-3 p-3 bg-white rounded box-shadow">
        <h6 class="border-bottom border-gray pb-2 mb-0">Recent updates</h6>
          {% for object in object_list %}
             <div class="media text-muted pt-3">
          <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded" src="">
          <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">{{ object.user }}</strong>
            {{ object.content }}
               <small class="d-block text-gray-dark mr-lg-2 py-2"> by - {{ object.user }} | {{ object.timestamp|timesince }} |
                <a href="{{ object.get_absolute_url }}">View</a></small>
          </p>
        </div>
          {% endfor %}

        <small class="d-block text-right mt-3">
          <a href="#">All updates</a>
        </small>
      </div>
        </div>
        <aside class="col-md-4 blog-sidebar" >
      <div class="my-3 p-3 bg-white rounded box-shadow">
        <h6 class="border-bottom border-gray pb-2 mb-0">Suggestions</h6>
        <div class="media text-muted pt-3">
          <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">

          <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
          <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <div class="d-flex justify-content-between align-items-center w-100">
              <strong class="text-gray-dark">Full Name</strong>
              <a href="#">Follow</a>
            </div>
            <span class="d-block">@username</span>
          </div>
        </div>
        <small class="d-block text-right mt-3">
          <a href="#">All suggestions</a>
        </small>
      </div>

        </aside>
        </div>
        </main>

{% endblock %}

templates/lowbar.html
  <div class="nav-scroller bg-white box-shadow">
      <nav class="nav nav-underline">
        <a class="nav-link active" href="#">Dashboard</a>
        <a class="nav-link" href="#">
          Friends
          <span class="badge badge-pill bg-light align-text-bottom">27</span>
        </a>
        <a class="nav-link" href="#">Explore</a>
        <a class="nav-link" href="#">Suggestions</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
        <a class="nav-link" href="#">Link</a>
      </nav>
    </div>

templates/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark" data-spy="affix">
      <a class="navbar-brand" href="{% url 'posts:post-list' %}">Academy Book</a>
      <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
        <span class="navbar-toggler-icon"></span>
      </button>
house
      <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">{{ title }} <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">{{ notify }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">{{ profile }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Switch account</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ settings }}</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
           <form id="navbar-search-form" method="GET" action="{% url "posts:search" %}" class="form-inline my-2 my-lg-1">
        <label>
            <input class="form-control mr-sm-2" type="text" name="q" placeholder="{{ search }}"/>
        </label>
        <input class="btn btn-outline-success my-2 my-sm-2" type="submit" value="{{ search }}"/>
               {% if request.user.is_authenticated %}
                    <a href="{% url 'profiles:logout' %}" class="btn btn-outline-success my-2 my-sm-0" >Logout</a>
                   {% else %}
                     <a href="{% url 'profiles:login' %}" class="btn btn-outline-success my-2 my-sm-0" >Login</a>
                    <a href="{% url 'profiles:register' %}" class="btn btn-outline-success my-2 my-sm-0" >Register</a>
               {% endif %}



    </form>
      </div>

</nav>

templates/translation.html
{% load i18n %}
<h1> {% trans "let's translate this" %}</h1>

    {% get_current_language as LANGUAGE_CODE %}
    <h1>{{ LANGUAGE_CODE }} </h1>
    <h1>{{ title }}</h1>

    <form class="form-control" action="{% url 'set_language' %}" method="post"> {% csrf_token %}
        <input type="hidden" name="text" value="{{ redirect_to }}"/>
        <select name="language" id="">
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for lang in languages %}
                <option value="{{ lang.code }}" {% if lang.code == LANGUAGE_CODE %} selected

                {% endif %} >
                {{ lang.name_local }} ({{ lang.code }})
                </option>
            {% endfor %}
        <input type="submit" value="Go">

        </select>

    </form>

        <div class="row" >
        <div class="col-md-8 blog-main">